#!/bin/bash
#
# BEGIN_COPYRIGHT
#
# Copyright (C) 2008-2015 SciDB, Inc.
# All Rights Reserved.
#
# SciDB is free software: you can redistribute it and/or modify
# it under the terms of the AFFERO GNU General Public License as published by
# the Free Software Foundation.
#
# SciDB is distributed "AS-IS" AND WITHOUT ANY WARRANTY OF ANY KIND,
# INCLUDING ANY IMPLIED WARRANTY OF MERCHANTABILITY,
# NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE. See
# the AFFERO GNU General Public License for the complete license terms.
#
# You should have received a copy of the AFFERO GNU General Public License
# along with SciDB.  If not, see <http://www.gnu.org/licenses/agpl-3.0.html>
#
# END_COPYRIGHT
#
################################################################################
# This is a debian postinst script that:
#
# Modifies the installed repository list file scidb.list by
# substituting for the string "OS" either ubuntu12.04 or ubuntu14.04
#
# Downloads paradigm4's apt-key
################################################################################
OSVERSION=`lsb_release -r -s`

sed -i "s/OS/ubuntu${OSVERSION}/" /etc/apt/sources.list.d/scidb.list

wget -O- https://downloads.paradigm4.com/key | apt-key add -
