# This sed script is used to allow for comparison of physical plans
# generated by _explain_physical in the test harness:
# # For Example:
# # >[pNode] physicalScan ddl 0 tile 1 children 0
# #      schema public.bb<v2:int64> [zpublic.bb=0:99 (VARIES:VARIES),100,0] ArrayId: VARIES UnversionedArrayId: VARIES Version: 0 Flags: 16 Distro: dist: hash ps: 1 ctx:  redun: 1 off: {} shift: 0 res: [0, 1, 2, 3] <v2:int64,EmptyTag:indicator NOT NULL>
# #      output full chunks: yes
# #      changes dstribution: no
# #      props sgm 1 sgo 1
# #      diout dist: hash ps: 1 ctx:  redun: 1 off: {} shift: 0 res: [0, 1, 2, 3]
# #      bound start {5, 0} end {10, 9} density 1 cells 60 chunks 1 est_bytes 2942
#
# Items marked as "VARIES" above are replaced with a static value
# So that test comparison can occur
# remove all lines not containing [pNode], or schema
/^\(>*\[pNode\]\| *schema\|{\)/!d
#
# Change the (curStart:curEnd) portion of the schema with (x:y)
s#([-0-9][0-9]*:[-0-9][0-9]*)#(x:y)#g
# Remove everthing after ArrayID
s# *\(ArrayId: \)[0-9][0-9]*.*##
